version: '3.8'
services:
  myblog_server:
    build: .
    image: myblog
    container_name: myblog_server
    ports:
      - "80:8080"
    links:
      - mysql_server
    environment:
      MYSQL_HOST: mysql_server
      MYSQL_DB: myblog_db
      MYSQL_USER: root
      MYSQL_PWD: YQYyqy171171
    volumes:
      - /opt/myblog_data:/opt/myblog/data
    depends_on:
      mysql_server:
        condition: service_healthy
    command: ["sh", "-c", "sleep 20 && your_start_command"]  # 延迟启动以确保 MySQL 完全启动

  mysql_server:
    image: mysql:8.0
    container_name: mysql_server
    volumes:
      - /opt/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: YQYyqy171171
      MYSQL_DATABASE: myblog_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
